language: java
notifications:
  slack:
    secure: NiXeJ2YlXgPTRk/iwo76XdTWXELGnu/wSX4ZT2N1Pmhkg0A2IExm4TkKhXVmSXoYPuiuF3/7BRf3VM4uRwLex/WkdEQXqwA3aXChNdkRBnRseUwEMBgNvKOVjZXExHzs91bH+wr4m7L1qqpvQikYOMtSsVc/4Oh8cTNUAeGITlc=
